//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidRailEmergencyManagement.KGWebService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://controller.kg.com/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://controller.kg.com/")]
    public partial class SQLException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sQLStateField;
        
        private int errorCodeField;
        
        private string messageField;
        
        private sqlException nextExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string SQLState {
            get {
                return this.sQLStateField;
            }
            set {
                this.sQLStateField = value;
                this.RaisePropertyChanged("SQLState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public sqlException nextException {
            get {
                return this.nextExceptionField;
            }
            set {
                this.nextExceptionField = value;
                this.RaisePropertyChanged("nextException");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://controller.kg.com/")]
    public partial class sqlException : exception {
        
        private sqlException nextExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public sqlException nextException {
            get {
                return this.nextExceptionField;
            }
            set {
                this.nextExceptionField = value;
                this.RaisePropertyChanged("nextException");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sqlException))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://controller.kg.com/")]
    public partial class exception : throwable {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(exception))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sqlException))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://controller.kg.com/")]
    public partial class throwable : object, System.ComponentModel.INotifyPropertyChanged {
        
        private stackTraceElement[] stackTraceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("stackTrace", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public stackTraceElement[] stackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
                this.RaisePropertyChanged("stackTrace");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://controller.kg.com/")]
    public partial class stackTraceElement : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://controller.kg.com/", ConfigurationName="KGWebService.KgServiceController")]
    public interface KgServiceController {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.kg.com/KgServiceController/getTunnelingIdRequest", ReplyAction="http://controller.kg.com/KgServiceController/getTunnelingIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RapidRailEmergencyManagement.KGWebService.getTunnelingIdResponse getTunnelingId(RapidRailEmergencyManagement.KGWebService.getTunnelingIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.kg.com/KgServiceController/getTunnelingIdRequest", ReplyAction="http://controller.kg.com/KgServiceController/getTunnelingIdResponse")]
        System.Threading.Tasks.Task<RapidRailEmergencyManagement.KGWebService.getTunnelingIdResponse> getTunnelingIdAsync(RapidRailEmergencyManagement.KGWebService.getTunnelingIdRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.kg.com/KgServiceController/isProjectExistRequest", ReplyAction="http://controller.kg.com/KgServiceController/isProjectExistResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RapidRailEmergencyManagement.KGWebService.isProjectExistResponse isProjectExist(RapidRailEmergencyManagement.KGWebService.isProjectExistRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.kg.com/KgServiceController/isProjectExistRequest", ReplyAction="http://controller.kg.com/KgServiceController/isProjectExistResponse")]
        System.Threading.Tasks.Task<RapidRailEmergencyManagement.KGWebService.isProjectExistResponse> isProjectExistAsync(RapidRailEmergencyManagement.KGWebService.isProjectExistRequest request);
        
        // CODEGEN: 参数“arg0”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.kg.com/KgServiceController/insertAlarmRequest", ReplyAction="http://controller.kg.com/KgServiceController/insertAlarmResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RapidRailEmergencyManagement.KGWebService.Exception), Action="http://controller.kg.com/KgServiceController/insertAlarm/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RapidRailEmergencyManagement.KGWebService.insertAlarmResponse insertAlarm(RapidRailEmergencyManagement.KGWebService.insertAlarmRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.kg.com/KgServiceController/insertAlarmRequest", ReplyAction="http://controller.kg.com/KgServiceController/insertAlarmResponse")]
        System.Threading.Tasks.Task<RapidRailEmergencyManagement.KGWebService.insertAlarmResponse> insertAlarmAsync(RapidRailEmergencyManagement.KGWebService.insertAlarmRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.kg.com/KgServiceController/initProjectRequest", ReplyAction="http://controller.kg.com/KgServiceController/initProjectResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RapidRailEmergencyManagement.KGWebService.Exception), Action="http://controller.kg.com/KgServiceController/initProject/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RapidRailEmergencyManagement.KGWebService.initProjectResponse initProject(RapidRailEmergencyManagement.KGWebService.initProjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.kg.com/KgServiceController/initProjectRequest", ReplyAction="http://controller.kg.com/KgServiceController/initProjectResponse")]
        System.Threading.Tasks.Task<RapidRailEmergencyManagement.KGWebService.initProjectResponse> initProjectAsync(RapidRailEmergencyManagement.KGWebService.initProjectRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.kg.com/KgServiceController/getLastestTunnelingTimeStampRequest", ReplyAction="http://controller.kg.com/KgServiceController/getLastestTunnelingTimeStampResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(RapidRailEmergencyManagement.KGWebService.SQLException), Action="http://controller.kg.com/KgServiceController/getLastestTunnelingTimeStamp/Fault/S" +
            "QLException", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RapidRailEmergencyManagement.KGWebService.getLastestTunnelingTimeStampResponse getLastestTunnelingTimeStamp(RapidRailEmergencyManagement.KGWebService.getLastestTunnelingTimeStampRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.kg.com/KgServiceController/getLastestTunnelingTimeStampRequest", ReplyAction="http://controller.kg.com/KgServiceController/getLastestTunnelingTimeStampResponse" +
            "")]
        System.Threading.Tasks.Task<RapidRailEmergencyManagement.KGWebService.getLastestTunnelingTimeStampResponse> getLastestTunnelingTimeStampAsync(RapidRailEmergencyManagement.KGWebService.getLastestTunnelingTimeStampRequest request);
        
        // CODEGEN: 参数“arg0”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.kg.com/KgServiceController/insertTunnelingRuntimeRequest", ReplyAction="http://controller.kg.com/KgServiceController/insertTunnelingRuntimeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RapidRailEmergencyManagement.KGWebService.Exception), Action="http://controller.kg.com/KgServiceController/insertTunnelingRuntime/Fault/Excepti" +
            "on", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RapidRailEmergencyManagement.KGWebService.insertTunnelingRuntimeResponse insertTunnelingRuntime(RapidRailEmergencyManagement.KGWebService.insertTunnelingRuntimeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.kg.com/KgServiceController/insertTunnelingRuntimeRequest", ReplyAction="http://controller.kg.com/KgServiceController/insertTunnelingRuntimeResponse")]
        System.Threading.Tasks.Task<RapidRailEmergencyManagement.KGWebService.insertTunnelingRuntimeResponse> insertTunnelingRuntimeAsync(RapidRailEmergencyManagement.KGWebService.insertTunnelingRuntimeRequest request);
        
        // CODEGEN: 参数“arg0”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.kg.com/KgServiceController/insertTunnelingHistoryRequest", ReplyAction="http://controller.kg.com/KgServiceController/insertTunnelingHistoryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RapidRailEmergencyManagement.KGWebService.Exception), Action="http://controller.kg.com/KgServiceController/insertTunnelingHistory/Fault/Excepti" +
            "on", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RapidRailEmergencyManagement.KGWebService.insertTunnelingHistoryResponse insertTunnelingHistory(RapidRailEmergencyManagement.KGWebService.insertTunnelingHistoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.kg.com/KgServiceController/insertTunnelingHistoryRequest", ReplyAction="http://controller.kg.com/KgServiceController/insertTunnelingHistoryResponse")]
        System.Threading.Tasks.Task<RapidRailEmergencyManagement.KGWebService.insertTunnelingHistoryResponse> insertTunnelingHistoryAsync(RapidRailEmergencyManagement.KGWebService.insertTunnelingHistoryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTunnelingId", WrapperNamespace="http://controller.kg.com/", IsWrapped=true)]
    public partial class getTunnelingIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.kg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getTunnelingIdRequest() {
        }
        
        public getTunnelingIdRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTunnelingIdResponse", WrapperNamespace="http://controller.kg.com/", IsWrapped=true)]
    public partial class getTunnelingIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.kg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public getTunnelingIdResponse() {
        }
        
        public getTunnelingIdResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="isProjectExist", WrapperNamespace="http://controller.kg.com/", IsWrapped=true)]
    public partial class isProjectExistRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.kg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public isProjectExistRequest() {
        }
        
        public isProjectExistRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="isProjectExistResponse", WrapperNamespace="http://controller.kg.com/", IsWrapped=true)]
    public partial class isProjectExistResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.kg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public isProjectExistResponse() {
        }
        
        public isProjectExistResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertAlarm", WrapperNamespace="http://controller.kg.com/", IsWrapped=true)]
    public partial class insertAlarmRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.kg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public insertAlarmRequest() {
        }
        
        public insertAlarmRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertAlarmResponse", WrapperNamespace="http://controller.kg.com/", IsWrapped=true)]
    public partial class insertAlarmResponse {
        
        public insertAlarmResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="initProject", WrapperNamespace="http://controller.kg.com/", IsWrapped=true)]
    public partial class initProjectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.kg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.kg.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.kg.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.kg.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.kg.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg4;
        
        public initProjectRequest() {
        }
        
        public initProjectRequest(string arg0, string arg1, string arg2, string arg3, string arg4) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="initProjectResponse", WrapperNamespace="http://controller.kg.com/", IsWrapped=true)]
    public partial class initProjectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.kg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public initProjectResponse() {
        }
        
        public initProjectResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLastestTunnelingTimeStamp", WrapperNamespace="http://controller.kg.com/", IsWrapped=true)]
    public partial class getLastestTunnelingTimeStampRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.kg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.kg.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        public getLastestTunnelingTimeStampRequest() {
        }
        
        public getLastestTunnelingTimeStampRequest(int arg0, int arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLastestTunnelingTimeStampResponse", WrapperNamespace="http://controller.kg.com/", IsWrapped=true)]
    public partial class getLastestTunnelingTimeStampResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.kg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime @return;
        
        public getLastestTunnelingTimeStampResponse() {
        }
        
        public getLastestTunnelingTimeStampResponse(System.DateTime @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertTunnelingRuntime", WrapperNamespace="http://controller.kg.com/", IsWrapped=true)]
    public partial class insertTunnelingRuntimeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.kg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public insertTunnelingRuntimeRequest() {
        }
        
        public insertTunnelingRuntimeRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertTunnelingRuntimeResponse", WrapperNamespace="http://controller.kg.com/", IsWrapped=true)]
    public partial class insertTunnelingRuntimeResponse {
        
        public insertTunnelingRuntimeResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertTunnelingHistory", WrapperNamespace="http://controller.kg.com/", IsWrapped=true)]
    public partial class insertTunnelingHistoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.kg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public insertTunnelingHistoryRequest() {
        }
        
        public insertTunnelingHistoryRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertTunnelingHistoryResponse", WrapperNamespace="http://controller.kg.com/", IsWrapped=true)]
    public partial class insertTunnelingHistoryResponse {
        
        public insertTunnelingHistoryResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KgServiceControllerChannel : RapidRailEmergencyManagement.KGWebService.KgServiceController, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KgServiceControllerClient : System.ServiceModel.ClientBase<RapidRailEmergencyManagement.KGWebService.KgServiceController>, RapidRailEmergencyManagement.KGWebService.KgServiceController {
        
        public KgServiceControllerClient() {
        }
        
        public KgServiceControllerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KgServiceControllerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KgServiceControllerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KgServiceControllerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RapidRailEmergencyManagement.KGWebService.getTunnelingIdResponse RapidRailEmergencyManagement.KGWebService.KgServiceController.getTunnelingId(RapidRailEmergencyManagement.KGWebService.getTunnelingIdRequest request) {
            return base.Channel.getTunnelingId(request);
        }
        
        public int getTunnelingId(string arg0) {
            RapidRailEmergencyManagement.KGWebService.getTunnelingIdRequest inValue = new RapidRailEmergencyManagement.KGWebService.getTunnelingIdRequest();
            inValue.arg0 = arg0;
            RapidRailEmergencyManagement.KGWebService.getTunnelingIdResponse retVal = ((RapidRailEmergencyManagement.KGWebService.KgServiceController)(this)).getTunnelingId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RapidRailEmergencyManagement.KGWebService.getTunnelingIdResponse> RapidRailEmergencyManagement.KGWebService.KgServiceController.getTunnelingIdAsync(RapidRailEmergencyManagement.KGWebService.getTunnelingIdRequest request) {
            return base.Channel.getTunnelingIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<RapidRailEmergencyManagement.KGWebService.getTunnelingIdResponse> getTunnelingIdAsync(string arg0) {
            RapidRailEmergencyManagement.KGWebService.getTunnelingIdRequest inValue = new RapidRailEmergencyManagement.KGWebService.getTunnelingIdRequest();
            inValue.arg0 = arg0;
            return ((RapidRailEmergencyManagement.KGWebService.KgServiceController)(this)).getTunnelingIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RapidRailEmergencyManagement.KGWebService.isProjectExistResponse RapidRailEmergencyManagement.KGWebService.KgServiceController.isProjectExist(RapidRailEmergencyManagement.KGWebService.isProjectExistRequest request) {
            return base.Channel.isProjectExist(request);
        }
        
        public int isProjectExist(string arg0) {
            RapidRailEmergencyManagement.KGWebService.isProjectExistRequest inValue = new RapidRailEmergencyManagement.KGWebService.isProjectExistRequest();
            inValue.arg0 = arg0;
            RapidRailEmergencyManagement.KGWebService.isProjectExistResponse retVal = ((RapidRailEmergencyManagement.KGWebService.KgServiceController)(this)).isProjectExist(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RapidRailEmergencyManagement.KGWebService.isProjectExistResponse> RapidRailEmergencyManagement.KGWebService.KgServiceController.isProjectExistAsync(RapidRailEmergencyManagement.KGWebService.isProjectExistRequest request) {
            return base.Channel.isProjectExistAsync(request);
        }
        
        public System.Threading.Tasks.Task<RapidRailEmergencyManagement.KGWebService.isProjectExistResponse> isProjectExistAsync(string arg0) {
            RapidRailEmergencyManagement.KGWebService.isProjectExistRequest inValue = new RapidRailEmergencyManagement.KGWebService.isProjectExistRequest();
            inValue.arg0 = arg0;
            return ((RapidRailEmergencyManagement.KGWebService.KgServiceController)(this)).isProjectExistAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RapidRailEmergencyManagement.KGWebService.insertAlarmResponse RapidRailEmergencyManagement.KGWebService.KgServiceController.insertAlarm(RapidRailEmergencyManagement.KGWebService.insertAlarmRequest request) {
            return base.Channel.insertAlarm(request);
        }
        
        public void insertAlarm(string arg0) {
            RapidRailEmergencyManagement.KGWebService.insertAlarmRequest inValue = new RapidRailEmergencyManagement.KGWebService.insertAlarmRequest();
            inValue.arg0 = arg0;
            RapidRailEmergencyManagement.KGWebService.insertAlarmResponse retVal = ((RapidRailEmergencyManagement.KGWebService.KgServiceController)(this)).insertAlarm(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RapidRailEmergencyManagement.KGWebService.insertAlarmResponse> RapidRailEmergencyManagement.KGWebService.KgServiceController.insertAlarmAsync(RapidRailEmergencyManagement.KGWebService.insertAlarmRequest request) {
            return base.Channel.insertAlarmAsync(request);
        }
        
        public System.Threading.Tasks.Task<RapidRailEmergencyManagement.KGWebService.insertAlarmResponse> insertAlarmAsync(string arg0) {
            RapidRailEmergencyManagement.KGWebService.insertAlarmRequest inValue = new RapidRailEmergencyManagement.KGWebService.insertAlarmRequest();
            inValue.arg0 = arg0;
            return ((RapidRailEmergencyManagement.KGWebService.KgServiceController)(this)).insertAlarmAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RapidRailEmergencyManagement.KGWebService.initProjectResponse RapidRailEmergencyManagement.KGWebService.KgServiceController.initProject(RapidRailEmergencyManagement.KGWebService.initProjectRequest request) {
            return base.Channel.initProject(request);
        }
        
        public int initProject(string arg0, string arg1, string arg2, string arg3, string arg4) {
            RapidRailEmergencyManagement.KGWebService.initProjectRequest inValue = new RapidRailEmergencyManagement.KGWebService.initProjectRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            RapidRailEmergencyManagement.KGWebService.initProjectResponse retVal = ((RapidRailEmergencyManagement.KGWebService.KgServiceController)(this)).initProject(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RapidRailEmergencyManagement.KGWebService.initProjectResponse> RapidRailEmergencyManagement.KGWebService.KgServiceController.initProjectAsync(RapidRailEmergencyManagement.KGWebService.initProjectRequest request) {
            return base.Channel.initProjectAsync(request);
        }
        
        public System.Threading.Tasks.Task<RapidRailEmergencyManagement.KGWebService.initProjectResponse> initProjectAsync(string arg0, string arg1, string arg2, string arg3, string arg4) {
            RapidRailEmergencyManagement.KGWebService.initProjectRequest inValue = new RapidRailEmergencyManagement.KGWebService.initProjectRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            return ((RapidRailEmergencyManagement.KGWebService.KgServiceController)(this)).initProjectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RapidRailEmergencyManagement.KGWebService.getLastestTunnelingTimeStampResponse RapidRailEmergencyManagement.KGWebService.KgServiceController.getLastestTunnelingTimeStamp(RapidRailEmergencyManagement.KGWebService.getLastestTunnelingTimeStampRequest request) {
            return base.Channel.getLastestTunnelingTimeStamp(request);
        }
        
        public System.DateTime getLastestTunnelingTimeStamp(int arg0, int arg1) {
            RapidRailEmergencyManagement.KGWebService.getLastestTunnelingTimeStampRequest inValue = new RapidRailEmergencyManagement.KGWebService.getLastestTunnelingTimeStampRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            RapidRailEmergencyManagement.KGWebService.getLastestTunnelingTimeStampResponse retVal = ((RapidRailEmergencyManagement.KGWebService.KgServiceController)(this)).getLastestTunnelingTimeStamp(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RapidRailEmergencyManagement.KGWebService.getLastestTunnelingTimeStampResponse> RapidRailEmergencyManagement.KGWebService.KgServiceController.getLastestTunnelingTimeStampAsync(RapidRailEmergencyManagement.KGWebService.getLastestTunnelingTimeStampRequest request) {
            return base.Channel.getLastestTunnelingTimeStampAsync(request);
        }
        
        public System.Threading.Tasks.Task<RapidRailEmergencyManagement.KGWebService.getLastestTunnelingTimeStampResponse> getLastestTunnelingTimeStampAsync(int arg0, int arg1) {
            RapidRailEmergencyManagement.KGWebService.getLastestTunnelingTimeStampRequest inValue = new RapidRailEmergencyManagement.KGWebService.getLastestTunnelingTimeStampRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((RapidRailEmergencyManagement.KGWebService.KgServiceController)(this)).getLastestTunnelingTimeStampAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RapidRailEmergencyManagement.KGWebService.insertTunnelingRuntimeResponse RapidRailEmergencyManagement.KGWebService.KgServiceController.insertTunnelingRuntime(RapidRailEmergencyManagement.KGWebService.insertTunnelingRuntimeRequest request) {
            return base.Channel.insertTunnelingRuntime(request);
        }
        
        public void insertTunnelingRuntime(string arg0) {
            RapidRailEmergencyManagement.KGWebService.insertTunnelingRuntimeRequest inValue = new RapidRailEmergencyManagement.KGWebService.insertTunnelingRuntimeRequest();
            inValue.arg0 = arg0;
            RapidRailEmergencyManagement.KGWebService.insertTunnelingRuntimeResponse retVal = ((RapidRailEmergencyManagement.KGWebService.KgServiceController)(this)).insertTunnelingRuntime(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RapidRailEmergencyManagement.KGWebService.insertTunnelingRuntimeResponse> RapidRailEmergencyManagement.KGWebService.KgServiceController.insertTunnelingRuntimeAsync(RapidRailEmergencyManagement.KGWebService.insertTunnelingRuntimeRequest request) {
            return base.Channel.insertTunnelingRuntimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<RapidRailEmergencyManagement.KGWebService.insertTunnelingRuntimeResponse> insertTunnelingRuntimeAsync(string arg0) {
            RapidRailEmergencyManagement.KGWebService.insertTunnelingRuntimeRequest inValue = new RapidRailEmergencyManagement.KGWebService.insertTunnelingRuntimeRequest();
            inValue.arg0 = arg0;
            return ((RapidRailEmergencyManagement.KGWebService.KgServiceController)(this)).insertTunnelingRuntimeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RapidRailEmergencyManagement.KGWebService.insertTunnelingHistoryResponse RapidRailEmergencyManagement.KGWebService.KgServiceController.insertTunnelingHistory(RapidRailEmergencyManagement.KGWebService.insertTunnelingHistoryRequest request) {
            return base.Channel.insertTunnelingHistory(request);
        }
        
        public void insertTunnelingHistory(string arg0) {
            RapidRailEmergencyManagement.KGWebService.insertTunnelingHistoryRequest inValue = new RapidRailEmergencyManagement.KGWebService.insertTunnelingHistoryRequest();
            inValue.arg0 = arg0;
            RapidRailEmergencyManagement.KGWebService.insertTunnelingHistoryResponse retVal = ((RapidRailEmergencyManagement.KGWebService.KgServiceController)(this)).insertTunnelingHistory(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RapidRailEmergencyManagement.KGWebService.insertTunnelingHistoryResponse> RapidRailEmergencyManagement.KGWebService.KgServiceController.insertTunnelingHistoryAsync(RapidRailEmergencyManagement.KGWebService.insertTunnelingHistoryRequest request) {
            return base.Channel.insertTunnelingHistoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<RapidRailEmergencyManagement.KGWebService.insertTunnelingHistoryResponse> insertTunnelingHistoryAsync(string arg0) {
            RapidRailEmergencyManagement.KGWebService.insertTunnelingHistoryRequest inValue = new RapidRailEmergencyManagement.KGWebService.insertTunnelingHistoryRequest();
            inValue.arg0 = arg0;
            return ((RapidRailEmergencyManagement.KGWebService.KgServiceController)(this)).insertTunnelingHistoryAsync(inValue);
        }
    }
}
